alias: Update Bins Tag
description: ""
trigger:
  - platform: time_pattern
    hours: /3
condition: []
action:
  - service: open_epaper_link.drawcustom
    target:
      entity_id: open_epaper_link.0000021A3FC03B10
    data:
      background: black
      rotate: 0
      payload:
        - type: line
          fill: red
          width: 3
          x_start: 5
          y_start: 56
          x_end: 121
          y_end: 56
        - type: line
          fill: red
          width: 3
          x_start: 168
          y_start: 56
          x_end: 290
          y_end: 56
        - type: line
          fill: red
          width: 3
          x_start: 148
          y_start: 3
          x_end: 148
          y_end: 34
        - type: line
          fill: red
          width: 3
          x_start: 148
          y_start: 60
          x_end: 148
          y_end: 123
        - type: rectangle
          outline: black
          fill: >-
            {{'black' if states('sensor.abfallrestmuell') == 'unknown' or
            states('sensor.abfallrestmuell') | int > 1 else 'red' }}
          width: 1
          x_start: 5
          y_start: 3
          x_end: 144
          y_end: 52
        - type: text
          value: Restmuell
          font: ppb.ttf
          x: 10
          "y": 8
          size: 18
          color: >-
            {{'white' if states('sensor.abfallrestmuell') == 'unknown' or
            states('sensor.abfallrestmuell') | int > 1 else 'white' }}
        - type: text
          value: >-
            {% if states('sensor.abfallrestmuell') == 'unknown' %}Unknown{% elif
            states('sensor.abfallrestmuell') | int == 0 %}Heute{% elif
            states('sensor.abfallrestmuell') | int == 1 %}Morgen{% else
            %}{{states('sensor.abfallrestmuell')}} Tage{% endif %}
          font: ppb.ttf
          x: 8
          "y": 33
          size: 18
          color: >-
            {{'white' if states('sensor.abfallrestmuell') == 'unknown' or
            states('sensor.abfallrestmuell') | int > 1 else 'white' }}
        - type: rectangle
          outline: black
          fill: >-
            {{'black' if states('sensor.abfallpapier') == 'unknown' or
            states('sensor.abfallpapier') | int > 1 else 'red' }}
          width: 1
          x_start: 152
          y_start: 3
          x_end: 290
          y_end: 52
        - type: text
          value: Papier
          font: ppb.ttf
          x: 180
          "y": 8
          size: 18
          color: >-
            {{'white' if states('sensor.abfallpapier') == 'unknown' or
            states('sensor.abfallpapier') | int > 1 else 'white' }}
        - type: text
          value: >-
            {% if states('sensor.abfallpapier') == 'unknown' %}Unknown{% elif
            states('sensor.abfallpapier') | int == 0 %}Heute{% elif
            states('sensor.abfallpapier') | int == 1 %}Morgen{% else
            %}{{states('sensor.abfallpapier')}} Tage{% endif %}
          font: ppb.ttf
          x: 180
          "y": 33
          size: 18
          color: >-
            {{'white' if states('sensor.abfallpapier') == 'unknown' or
            states('sensor.abfallpapier') | int > 1 else 'white' }}
        - type: rectangle
          outline: black
          fill: >-
            {{'black' if states('sensor.abfallgelbersack') == 'unknown' or
            states('sensor.abfallgelbersack') | int > 1 else 'red' }}
          width: 1
          x_start: 5
          y_start: 60
          x_end: 144
          y_end: 107
        - type: text
          value: Gelber S.
          font: ppb.ttf
          x: 10
          "y": 70
          size: 18
          color: >-
            {{'white' if states('sensor.abfallgelbersack') == 'unknown' or
            states('sensor.abfallgelbersack') | int > 1 else 'white' }}
        - type: text
          value: >-
            {% if states('sensor.abfallgelbersack') == 'unknown' %}Unknown{%
            elif states('sensor.abfallgelbersack') | int == 0 %}Heute{% elif
            states('sensor.abfallgelbersack') | int == 1 %}Morgen{% else
            %}{{states('sensor.abfallgelbersack')}} Tage{% endif %}
          font: ppb.ttf
          x: 10
          "y": 90
          size: 18
          color: >-
            {{'white' if states('sensor.abfallgelbersack') == 'unknown' or
            states('sensor.abfallgelbersack') | int > 1 else 'white' }}
        - type: rectangle
          outline: black
          fill: >-
            {{'black' if states('sensor.abfallgelbersack') == 'unknown' or
            states('sensor.abfallgelbersack') | int > 1 else 'red' }}
          width: 1
          x_start: 152
          y_start: 60
          x_end: 290
          y_end: 107
        - type: text
          value: Bio
          font: ppb.ttf
          x: 180
          "y": 70
          size: 18
          color: >-
            {{'white' if states('sensor.abfallpapier') == 'unknown' or
            states('sensor.abfallbio') | int > 1 else 'white' }}
        - type: text
          value: >-
            {% if states('sensor.abfallbio') == 'unknown' %}Unknown{% elif
            states('sensor.abfallbio') | int == 0 %}Heute{% elif
            states('sensor.abfallbio') | int == 1 %}Morgen{% else
            %}{{states('sensor.abfallbio')}} Tage{% endif %}
          font: ppb.ttf
          x: 180
          "y": 90
          size: 18
          color: >-
            {{'white' if states('sensor.abfallbio') == 'unknown' or
            states('sensor.abfallbio') | int > 1 else 'white' }}
        - type: icon
          value: circle
          x: 113
          "y": 20
          size: 70
          color: black
        - type: icon
          value: trash-can
          x: 123
          "y": 30
          size: 50
          color: >-
            {{ 'red' if (([(14 if states('sensor.abfallrestmuell') == 'unknown'
            else states('sensor.abfallrestmuell')),(14 if
            states('sensor.abfallpapier') == 'unknown' else
            states('sensor.abfallpapier')),(14 if states('sensor.abfallbio') ==
            'unknown' else states('sensor.abfallbio')),(14 if
            states('sensor.abfallgelbersack') == 'unknown' else
            states('sensor.abfallgelbersack')) ]) | min ) | int < 2 else 'white'
            }}
        - type: rectangle
          outline: red
          fill: white
          width: 2
          x_start: 1
          y_start: 110
          x_end: 293
          y_end: 126
        - type: text
          value: "{{ states('sensor.0000021A3FC03B10_temperature') | string }} °"
          font: ppb.ttf
          x: 265
          "y": 114
          size: 13
          color: black
        - type: icon
          value: thermometer
          x: 250
          "y": 111
          size: 13
          color: red
        - type: icon
          value: battery-medium
          x: 3
          "y": 112
          size: 13
          color: red
        - type: text
          value: "{{ states('sensor.0000021A3FC03B10_battery') | string }} %"
          font: ppb.ttf
          x: 20
          "y": 114
          size: 13
          color: black
        - type: icon
          value: wifi
          x: 60
          "y": 111
          size: 13
          color: red
        - type: text
          value: "{{ states('sensor.0000021a3fc03b10_rssi') | string }} dB"
          font: ppb.ttf
          x: 77
          "y": 114
          size: 13
          color: black
        - type: icon
          value: refresh
          x: 130
          "y": 111
          size: 13
          color: red
        - type: text
          value: "{{ states('sensor.time')}}"
          font: ppb.ttf
          x: 150
          "y": 114
          size: 13
          color: black
mode: single
